import type { Metadata } from "next";
import {Poppins, Questrial} from "next/font/google";
import "./globals.css";
import NavigationComponent from "@/aymericpixel/app/ui/foundation/navigationComponent";
import FooterComponent from "@/aymericpixel/app/ui/foundation/footerComponent";
import {ReactNode} from "react";


const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
	weight: "400",
});

const poppins = Poppins({
	variable: "--font-poppins",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fr" className={`${questrial.className} ${poppins.variable}`}>
      <body>
        <NavigationComponent />
        <div className="superContainer">
	        {children}
        </div>
        <FooterComponent />
      </body>
    </html>
  );
}
